### ISSUE TITLE
Server Side Rendering Incomplete on ChromePicker (and others)

### ISSUE THREAD

**Issue by develerltd** [casesandberg/react-color#127]
Hi,

I get a warning from React (0.14) that background-image is null when rendered server side, but contains the image client-side meaning that they are rendering differently. This makes it a pain to use for isomorphic apps, as there will always be this warning here.

**Comment by casesandberg** [comment]
What's the full trace?

**Comment by e-karma** [comment]
Hi Again!

It appears we have encountered the same issue (ISO incompatible). 
any idea if fixing this was accomplished, still of interest or in the works?

If not overly complex we can send a PR & try to help with a brief overview of needed steps.

Thanks!

**Comment by ryan-codingintrigue** [comment]
@casesandberg I did a bit of research into this. The problem lies in [helpers/checkboard.js#L4](https://github.com/casesandberg/react-color/blob/443a84fa3f05db2e6dfa350f25c2d481960d993d/src/helpers/checkboard.js#L4) which is using a HTML5 canvas to generate a data-url.

I noticed that this replaced code which rendered a React component. Rather than reinstating this, which would take a lot of work, is there merit in a PR which introduces [node-canvas](https://github.com/Automattic/node-canvas) for server-side rendering? Or would you be reluctant to add a server-only dependency?

**Comment by casesandberg** [comment]
I definitely don't want to install a dependency just for SSR. I will have to look into node-canvas though, because if the API is the same as the browser I can put in a prop which one could map the node-canvas dep to that would replace the browser canvas.

**Comment by casesandberg** [comment]
Just taking a quick look at the [exmples](https://github.com/Automattic/node-canvas#example) it seems like it would be quite easy to do by passing `node-canvas` though. Any thoughts on the API:

```
import Canvas from 'node-canvas'
import { SketchPicker } from 'react-color'

<SketchPicker server={{ Canvas }} /> 
// or
<SketchPicker ssr={{ Canvas }} /> 
// or
<SketchPicker renderers={{ canvas: Canvas }} /> 
```

**Comment by ryan-codingintrigue** [comment]
This looks great, thanks! Personally, I would prefer:
```js
<SketchPicker renderers={{ canvas: Canvas }} /> 
```
It leaves more scope for further server changes in the future, plus I think it reads better than server/ssr.

I implemented node-canvas in my own fork: https://github.com/ryan-codingintrigue/react-color
It works OK, except I'm seeing a difference in the Data URIs generated on server/client. I've logged a bug on their repo: https://github.com/Automattic/node-canvas/issues/853.

Thanks again for looking at this. It's important for me to match my server/client in my React projects 😄

**Comment by casesandberg** [comment]
This is live in `react-color@2.9.0`!

**Comment by ryan-codingintrigue** [comment]
Awesome, thank you so much! Just FYI, I couldn't get the Data URI returned from `node-canvas` to match the Data URI generated in my browser, but using this API I was able to create a stub class for the server:

```js
const dataUrl = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMUlEQVQ4T2NkYGAQYcAP3uCTZhw1gGGYhAGBZIA/nYDCgBDAm9BGDWAAJyRCgLaBCAAgXwixzAS0pgAAAABJRU5ErkJggg==";

export default class ServerCanvas {
    constructor() {
        this.toDataURL = () => dataUrl;
        this.getContext = () => ({
            fillRect: () => {},
            translate: () => {}
        });
    }
}
```

Since I'm only using the `ChromePicker` and one browser, this suits my requirements for allowing React to match server/client

**Comment by casesandberg** [comment]
Thats perfect 🙌

**Comment by coreyward** [comment]
I'm having this issue as well. Would it not be possible to have the component automatically return a pre-rendered dataUrl like @ryan-codingintrigue does above instead of returning `null` here?

https://github.com/casesandberg/react-color/blob/0657c78ef80d1144495e45aff6555f163eb7b240/src/helpers/checkboard.js#L4-L6
