### ISSUE TITLE
few problems with react 15.0.2

### ISSUE THREAD

**Issue by kennedy0527** [casesandberg/react-color#152]
I just updated react to 15.0.2 and react-color to 2.1.0

now I face some problems

First, I use `color.rgb` to get color I choose but picker seem cannot get the value correctly (or other problems?!) cause it couldn't update properly, alpha cannot slide and circle pointer cannot move
but I still can get the color value 

same problem occurred by using `color.hsl` too

Second, HEX field show double # like `##FFFFFF`, it isn't correct, is it ?
official site also got this problem 

Third, in chrome picker, the button which control showing HEX, RGBA, HSL field, got some wired problems
hover cause it flash?! and nothing happen when clicked it ... (browser problem..?!!) 
Im testing on Safari 9.1

Fourth, same problem #114, I fixed it by modify all `Absolute: 0 0 0 0` to `Absolute: 0px 0px 0px 0px`

**Comment by islemaster** [comment]
Re: The change to the hex field, it seems like the change to color.hex to include its own `#` was intentional (per https://github.com/casesandberg/react-color/issues/51) but the previously published npm package didn't have the fix. We had to adjust our own application here: https://github.com/code-dot-org/code-dot-org/pull/8178#discussion_r61930040.  I didn't realize this was causing a bug internal to this project too.  Thanks for reporting it!

**Comment by btjones** [comment]
I'm seeing the flashing issue as well with the Chrome picker on mouse over:

![flash](https://cloud.githubusercontent.com/assets/155808/15330236/fba37bd0-1c29-11e6-87a0-63da637b68b5.gif)

**Comment by casesandberg** [comment]
This has all been fixed if you update to `react-color@2.2.4`
