### ISSUE TITLE
Checkboard.js at Line 27 Uncaught TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by draftstudios** [casesandberg/react-color#195]
I'm on React 14.8 and react-color@2.0.0, just wondering if you could help me pinpoint why I'm getting:

Checkboard.js at Line 27 Uncaught TypeError: Super expression must either be null or a function, not undefined

Whenever importing from 'react-color'?

Did some global npm dependency cleanup today and things just started not working :( Thanks!

**Comment by draftstudios** [comment]
Great component btw!!~ was working for the last few days, I'm pretty sure I messed something up.

**Comment by casesandberg** [comment]
Is this still an issue if you update to the latest version?

**Comment by edrpls** [comment]
@casesandberg I'm using the same version as @draftstudios and I'm getting the same error with 2.2.6, it's really weird, though, because it worked right after I upgraded react-color with npm install react-color --save, but after going back to that branch, deleting node_modules and running npm install on my project, the error came back, even though the installed version is still 2.2.6.

**Comment by casesandberg** [comment]
Hmmm, maybe an NPM caching issue? Do you have react-color installed globally by chance? I know there is a way to clear the cache somehow.
