### ISSUE TITLE
Alpha slider in Sketch component is not working

### ISSUE THREAD

**Issue by tobias-kuendig** [casesandberg/react-color#24]
The value of the alpha slider in the Sketch component cannot be modified. 

This bug appears on the demo website too: https://casesandberg.github.io/react-color/#examples
See `SketchExample`.

**Comment by thataustin** [comment]
Are you sure it's broken?  I know the example isn't working, but I think that's just because the onChange callback is just ignoring the alpha value in that example.  See how it's only capturing the hex value:

```
  handleChange(color) {
    this.setState({ color: '#' + color.hex });
  }
```

That method would need to use `color.rgb` or `color.hsl` instead of `color.hex`, and I think it would work.
Know what I mean?
