### ISSUE TITLE
Problems using Saturation and Hue common components

### ISSUE THREAD

**Issue by Joelgullander** [casesandberg/react-color#304]
Your documentation is confusing. 

First off, importing Hue and including it by `<Hue /> `will not work as it states in the documentation, however by importing HuePicker and including it by `<HuePicker />` seems to work. 

I need three sliders, one for Hue, one for Saturation and one for brightness. 

However, I cant include `<Saturation />` nor can I include `<SaturationPicker />` as it gives me the error: 
`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ColorControl`.`

So how would I accomplish using the HuePicker and adding two sliders for Saturation and Lightness?

**Comment by casesandberg** [comment]
There is no `SaturationPicker`, that error you are getting is because you are trying to use undefined as a component definition. 

You will want to use Saturation and Hue from the custom components section. The reason you don't see anything is because you have to wrap them each in digs that have position relative and a width and height set. You can take a look at any of the other color pickers to see how thy are used.
