### ISSUE TITLE
Broken material-colors API

### ISSUE THREAD

**Issue by echenley** [casesandberg/react-color#318]
[Material Colors](https://github.com/shuhei/material-colors) changed their es2015 API. [This line](https://github.com/casesandberg/react-color/blob/master/src/components/circle/Circle.js#L4) needs to be changed to:

```js
import * as material from 'material-colors'
```

See https://github.com/shuhei/material-colors/issues/16.

**Comment by shuhei** [comment]
The es2015 API has been like that from its beginning. I just changed const to var.

**Comment by casesandberg** [comment]
Fixed in `react-color@2.11.1`

**Comment by echenley** [comment]
@casesandberg Ahh, shoot. It turns out this is an issue between Webpack 1 and 2. @shuhei has removed the ES6 module: https://github.com/shuhei/material-colors/issues/16. Your change should probably be reverted.

I believe the change I suggested would have broken for Webpack 1 projects anyway.

**Comment by shuhei** [comment]
I checked out this repo and made sure that `npm test` worked against the latest version of material-colors.

**Comment by shuhei** [comment]
And I think both works well in webpack 1 because [those `import`s look almost same when transpiled into CommonJS ](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=true&loose=false&spec=false&code=import%20*%20as%20a%20from%20'a'%3B%0Aimport%20b%20from%20'b'%3B).
