### ISSUE TITLE
Breaks if the default color is #FFFFFF or #000000

### ISSUE THREAD

**Issue by adeelraza** [casesandberg/react-color#34]
The color picker doesn't work if the default color passed is #FFFFFF or #000000. On changing the color, it returns NaNNaNNaN.

**Comment by zainzafar** [comment]
+1

**Comment by krivinarius** [comment]
+1

**Comment by rickyvetter** [comment]
This should be fixed here https://github.com/casesandberg/react-color/commit/a373f92821b2407a287719f296c6dee4af5edb19

**Comment by adeelraza** [comment]
Thanks @rickyvetter :+1:

**Comment by casesandberg** [comment]
This was fixed in `react-color@1.0.6` ! Thanks for the hlp @rickyvetter

**Comment by devdoshi** [comment]
I'm stuck on ~1.0.6 and I still have this issue. If it's related to the oldHue issue, this file looks like it was reverted after the fix @rickyvetter referenced:
https://github.com/casesandberg/react-color/blob/71dfbdbcdc1bb504f837044e76c803ddca441b1d/lib/helpers/color.js#L31

Is there anyway this can be fixed in the 1.0.x versions?
