### ISSUE TITLE
Add className in props

### ISSUE THREAD

**Issue by searene** [casesandberg/react-color#393]
Hi,

Could you add className to props of those react color components? So I can use them like this:

```javascript
import React from 'react';
import { SketchPicker } from 'react-color';

class Component extends React.Component {

  render() {
    return <SketchPicker className="my-sketch-picker" />;
  }
}
```

Without it StyledComponents cannot work: [https://github.com/styled-components/styled-components/issues/1086](https://github.com/styled-components/styled-components/issues/1086)

And a custom className may also make the work much easier for a lot of people.

Thanks for considering it.

Regards,
Searene

**Comment by SpencerDawson** [comment]
Unless I've misread here, ColorWrap [passes all props it receives](https://github.com/casesandberg/react-color/blob/b89a69afb27166dda41ed81db9706eba8cfa35d8/src/components/common/ColorWrap.js#L52) down to it's child, unless you are referring to each individual component inside, say, `SketchPicker`.

As per your remark on that issue, you could create your own Picker using the provided components and pass them `className` as needed, since each default picker provided is passed to `colorWrap`.

**Comment by casesandberg** [comment]
Yep, this makes a lot of sense to me! As Spencer pointed out, color wrap already passes it down, so all I had to do was set it on each of the pickers root divs!

**Comment by casesandberg** [comment]
Merged in https://github.com/casesandberg/react-color/pull/403
