### ISSUE TITLE
Update to React 16

### ISSUE THREAD

**Issue by dsumer** [casesandberg/react-color#458]
Are you planning to update to React 16?

Cheers!
And thx for this awesome library! :)

**Comment by elvisvoer** [comment]
@dsumer are you experiencing the same issue as fixed in #466  ?

**Comment by glennpatrickryan** [comment]
React 16.9.0 has been released! :) This will result in a warning regarding any components using the `componentWillReceiveProps` lifecycle methods. I figured this issue is essentially a follow up once @dsumer's question above is answered. Thanks.
![image](https://user-images.githubusercontent.com/44648194/62786752-401a4b00-ba91-11e9-8444-90ea9ff3c96f.png)

**Comment by CyanoFresh** [comment]
need an update (

**Comment by casesandberg** [comment]
This was fixed with https://github.com/casesandberg/react-color/pull/662 and will be released shortly as `react-color@2.18.0`
