### ISSUE TITLE
On custom color component, hue seems to jump around when changing saturation

### ISSUE THREAD

**Issue by m10** [casesandberg/react-color#465]
I created a cutom colorpicker with the hue and saturation compoents. 
The hue changes when dragging around in saturation
https://codesandbox.io/s/jlykw9983y

steps to reproduce

- change hue
- drag around in saturation (especially left and bottom area)
- watch hue change

ref: #163

**Comment by m10** [comment]
I updated the examples dependencies. Especially it now uses `react-color@3.0.0-beta.3`.
The jumpyness remains.. https://codesandbox.io/s/jq5l8om25

**Comment by ldanet** [comment]
This is because RGB or hex color don't hold accurate information about hue. The color picker is given a hex color and has to derive hue from it. The less saturated the color is, the more inaccurate the hue will be. What hue is `#000`? Is it red, is it blue? There is no way to tell. The color picker does not hold an internal hue state so it has to get the information from the color you pass to it.

On the other hand, HSL color does keep an accurate hue value, even if there is no saturation at all.
One workaround would be to store the whole color object the picker gives back to you in the state and feed it the HSL one while using the hex where you need it.
https://codesandbox.io/s/vq7n68pzp0

**Comment by m10** [comment]
is it not possible to store the old hue e.g. inside the hue slider or customPicker hoc. If this one "fits" to the new hex value keep the old hue?

**Comment by casesandberg** [comment]
This is being actively developed in v3.0.0
