### ISSUE TITLE
SketchComponent presetColors updating DOM improperly

### ISSUE THREAD

**Issue by MaximumCrash** [casesandberg/react-color#487]
Hello, 

Whenever I change a color using the Sketch color picker my preset colors get updated with a new array of colors based on the current palette. However it seems there's extra colors being added to the DOM whenever I change the color. The array I'm feeding in is correct and React picks up my new colors, but the DOM seems to have extra colors that aren't a part of the preset color array I feed in. I've attached photos of before and after. 

**Before**
![screen shot 2018-03-12 at 10 03 27 am](https://user-images.githubusercontent.com/9157341/37288215-1a24ad0e-25dd-11e8-8372-2d5c39b88520.png)
**After**
![screen shot 2018-03-12 at 10 03 37 am](https://user-images.githubusercontent.com/9157341/37288221-1e40b3ec-25dd-11e8-8796-10772063f71a.png)

**Comment by casesandberg** [comment]
Can you post a code snippet of how you are using it?

**Comment by MaximumCrash** [comment]
@casesandberg I figured it out! 
It seems that my server was feeding in some undefined's as colors. The array was valid, but the color being read wasn't.

**Comment by vasuchawla** [comment]
for those coming here because they are dynamically populating the preset array and the same color repeat multiple times in the array, this scenario also causes this problem, in this case instead of creating an array of string hex codes, create the array of objects where the object is `{color: "#hex", title:"some_unique_title"}`
