### ISSUE TITLE
Github and Twitter pickers do not highlight active colour on init

### ISSUE THREAD

**Issue by tinacious** [casesandberg/react-color#521]
When initialized with prop `color`, the Github and Twitter pickers do not highlight the active colour.

All of the other colour pickers appear to update their active colour state, highlighting the active one.

This issue can be easily reproduced in [the demo](https://casesandberg.github.io/react-color/#api-color):

- Select a colour in the Github picker (or the Twitter picker)
- Copy its hex value from any of the pickers that display it to your clipboard
- Choose a different colour by clicking any of the pickers
- Paste the copied colour from your clipboard into one of the pickers that support receiving hex values

Results:

- Twitter does not update its active colour state
- Github does not update its active colour state
- Circle **does** update its active colour state (as do all the others)

Expected results (when receiving one of its included colours):

- Github picker has the 2px white outline 
- Twitter picker has the active/hover state

**Comment by jalmarazg** [comment]
Hello. I think the native behavior of these components is to, first after being selected stay highlighted ant then, after clicking any other element (Even if they are not the color pickers) the highlights disappear. 

I don't know If this is what the creator intended but, If it's not, I think there should be a way to, in order to update the colors, modify the state of those components to "re-highlight" the choice. 

I think I actually works like this because of the "limited pallete" the pickers have.

**Comment by casesandberg** [comment]
This is indeed the expected behaviour and is a bug. I am tagging it in the next release to make sure it gets fixed.
