### ISSUE TITLE
Slider is falling off 

### ISSUE THREAD

**Issue by yotester** [casesandberg/react-color#562]
Can reproduce this issue here: https://casesandberg.github.io/react-color/
Enter #00000 in HEX and using UP Arrow navigate to H and enter 500 and hit Tab.
The slider (white dot) falls off the Color section.  

<img width="1276" alt="slider_fall_off" src="https://user-images.githubusercontent.com/12789813/49835120-dca21700-fd63-11e8-8cc9-afcc9e226d22.png">

**Comment by casesandberg** [comment]
Fantastic catch! We are working on the new 3.0.0 of this library and have put in a guard on all inputs to not accept values over their appropriate amounts: https://github.com/casesandberg/react-color/blob/3.0.0/packages/core/Input/test.js#L74-L78. I am going to close this as it will be fixed in the new version!
