### ISSUE TITLE
Using babel-plugin-macros to optimize bundle size after named imports from 2.x

### ISSUE THREAD

**Issue by mi6gan** [casesandberg/react-color#652]
At the moment, v2.x of the library bundled to commonjs module. As a result, importing of color pickers to es6 modules causes an inclusion of all exported components. It sufficiently increases amount of dead code in an output bundle (~150kb extra).

I know that you are working on version 3.x and it seems the problem will be solved by the release. But what about those folks who will not able to switch from 2.x immediately but still may want to have an option to reduce output bundle size?

I solved this problem by using [babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros) and writing this macro: https://github.com/redchiliorg/seine/tree/master/packages/helpers/react-color.macro

This macro is documented and published on npm. Probably, you would mention it in your 2.x documentation? I saw some issues (https://github.com/casesandberg/react-color/issues/504 for example) related to the problem, so the solution would be very useful in my opinion.

By the way, there are alternative solutions I suggest in the readme text of the macro package. They do not need babel-plugin-macros at all (in case it can't be used)

**Comment by casesandberg** [comment]
Thanks @mi6gan! This is currently a big issue because the entire project is still a commonJS module. [The docs were updated a while ago](https://github.com/casesandberg/react-color/blob/master/docs/documentation/02.02-include.md) with the proper install instructions to target specific pickers however it seems the code to update the documentation site is broken 😅The project will be an es6 module in the new 3.0.0 release so this will no longer be an issue then.
