### ISSUE TITLE
Picker does not close

### ISSUE THREAD

**Issue by kumarharsh** [casesandberg/react-color#67]
I am not able to close the pickers I open by clicking outside the picker element.

This is because I have put the picker in a component which has `transform` applied to an ancestor. Therefore, the `cover` element in Picker, which has a `position: fixed` actually starts behaving like a `position: absolute` element (transforms change the container element of fixed-pos elements)

![screenshot 43](https://cloud.githubusercontent.com/assets/760112/12080442/26a2a2ac-b280-11e5-9742-c3b12e6ed584.png)

**Comment by casesandberg** [comment]
I would suggest not using the built in hide / display functinality because the cover gets messed up as you are seeing now. You can control the hide / show functionality via the `display` prop. Set a bool state in your component and you can use that to control the display. When using the display prop it removes the built-in cover so you shouldnt run into this issue.
```
<ColorPicker display={ this.state.displayColorPicker } type="sketch" />
```
You can then create your own cover that is outside of the transform that changes the state to false on click.

**Comment by kumarharsh** [comment]
I am using the `display` property already. This is my code:

```jsx
  <ColorPicker
    display={ this.state.showPicker }
    position="below"
    positionCSS={styles.swatchPicker}
    type="chrome"
    onChangeComplete={this._handleChange}
    onClose={this._handleClose}
    color={this.state.color}
  />
```

**Comment by casesandberg** [comment]
Did you create your own overlay that toggles the state of `showPicker`?

**Comment by kumarharsh** [comment]
@casesandberg Sorry, I was not able to respond to you earlier. If I am understanding you correctly from your [comment](https://github.com/casesandberg/react-color/issues/67#issuecomment-168543161), if I set a `display` prop, the `cover` should not be rendered.

But then, there is no such control in the code, i.e, the cover seems to always be rendered

https://github.com/casesandberg/react-color/blob/c20b64962be65a151d47ab6ccff7bc2152196da1/src/components/ChromePicker.js#L144

**Comment by brucedlukens** [comment]
The issue with using this as a solution @casesandberg is that it's not really an "onblur" type of situation. A user doesn't want to have to click twice to click a button outside of the color picker. For example, a user has a color picker open below a series of buttons. With the solution that's proposed, the user would have to click the buttons (actually clicking the glass pane div) which would close the color picker. They then have to click the buttons again for the button click to register.
This seems very hacky and not intuitive at all. I'm not sure what the solution is since "focusing" a div seems difficult so "onblur" won't really work correctly.

**Comment by brucedlukens** [comment]
I have actually figured out a good way of doing this that functions (I believe) as a user expects:
Here's some code to show it:

```
if (this.state.display) {
      colorPicker = <div ref={this.divRefFunction} onBlur={this.handleClose}>
        <SketchPicker color={this.props.color}
                                position={this.props.position ? this.props.position : 'bottom'}
                                presetColors={this.props.presetColors}
                                onChange={this.handleColorChange}/>
      </div>;
    }
```

That colorPicker component goes into the render. Now you also have these functions:

```
/**
   * Function that gets called when the color picker gets closed.  Used to set display state to false.
   * @param {Event} event - Mouse click event
   */
  handleClose(event) {
    this.setState({display: false});
  }

/**
   * callback for ref
   *
   * @param {Element} div - div element
   */
  divRefFunction(div) {
    if (div) {
      div.focus();
    }
  }
```

This successfully creates the react-color component only when it needs to be displayed, and then it also acts as an "onblur" element and hides the component when the user clicks anywhere else.

**Comment by arecvlohe** [comment]
I think the easiest way to handle this is to put a wrapper around the color picker, which you already do so that it displays above content around it. Then just apply a `onMouseLeave` event to close it. I think this is better than having to create refs for each color picker. This will create the `onBlur` effect which I think is ideal.

`components.js`
```
export const ColorPickerWrapper = styled.div`
  position: absolute;
  z-index: 2;
`;

export const ColorPicker = ({ onMouseLeave, onChange, color }) => (
  <ColorPickerWrapper onMouseLeave={onMouseLeave}>
    <BlockPicker color={color} colors={defaultColors} onChangeComplete={onChange} triangle="hide" />
  </ColorPickerWrapper>
);
```
`component.js`
```
{showBorderPicker && (
  <ColorPicker
     color={styles.borderColor}
     onChange={handleChangeStyles(['event', 'styles', 'borderColor'])}
     onMouseLeave={handleShowPicker('showBorderPicker')}
 />
)}
```

**Comment by liziver** [comment]
This recipe can truly achieve the onBlur effect:
 `constructor(){
    this.swatchContainer = React.createRef();
    this.state={
        showColorPicker:false
    }
}
toggleColorPicker=()=>{
    this.setState(prevState=>({
        showColorPicker:!prevState.showColorPicker;
    }),()=>{
        this.swatchContainer.current.focus();
    });
}
hideColorPicker=()=>{
    this.setState({showColorPicker:false});
}
render(){
    return(
        <div>
            <div onClick={this.toggleColorPicker}></div>
            <div style={{"display":this.state.showColorPicker?"block":"none"}} tabIndex="0" onBlur={this.hideColorPicker} ref={this.swatchContainer} >
                <SwatchesPicker/>
            </div>
        </div>
    )
}`
The most important thing is to add tabIndex="0" on the picker container so the container can be focused and blurred.

**Comment by Dror-Bar** [comment]
@liziver Doesn't work. Clicking on the colors squares or the R G B numbers loses focus.

**Comment by liziver** [comment]
You are right, it does lose focus. I fixed it by adding a id attribute to the container, and only allow the picker to disappear when the user click outside of the box. See the code above. Thanks for pointing it out!

**Comment by Dror-Bar** [comment]
@liziver Nice trick, thanks for sharing. I had a solution of my own using onMouseEnter and onMouseLeave, but your seems better / simpler.
